# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy package files and config
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Production install
RUN npm prune --production

ENTRYPOINT ["node", "dist/index.js"]
